//export const FETCH_RECIPES_PENDING = 'FETCH_RECIPES_PENDING';
////export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
//export const FETCH_RECIPES_ERROR = 'FETCH_RECIPES_ERROR';


export const LOAD_RECIPES = 'LOAD_RECIPES'
export const ADD_RECIPE = 'ADD_RECIPE'
export const TOGGLE_RECIPE = 'TOGGLE_RECIPE'